name: Laravel Test Suite

on:
  workflow_dispatch:


jobs:
  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        volumes:
          - ./mysql-test-data:/docker-entrypoint-initdb.d

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, mysql, pdo, pdo_mysql, bcmath, ctype, fileinfo, json, tokenizer, openssl
          coverage: none
          tools: composer:v2

      - name: Copy .env
        run: |
          cp .env.testing .env

      - name: Setup Environment Variables
        run: |
          echo "APP_NAME=Laravel" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_test" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=password" >> .env
          
          # Same for testing environment
          echo "APP_ENV=testing" >> .env.testing
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=127.0.0.1" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=laravel_test" >> .env.testing
          echo "DB_USERNAME=laravel" >> .env.testing
          echo "DB_PASSWORD=password" >> .env.testing


      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-scripts


      - name: Prepare database
        run: |
          # Wait for MySQL to be ready
           while ! mysqladmin ping -h127.0.0.1 -ularavel -ppassword --silent; do
              sleep 1
          done
          
          echo "Listing existing tables..."
          mysql -h127.0.0.1 -ularavel -ppassword laravel_test -e "SHOW TABLES;"
          php artisan migrate
         

      - name: Generate app key
        run: php artisan key:generate

      - name: Run composer scripts
        run: composer run-script post-autoload-dump

      - name: Execute tests
        run: |
          php artisan test --env=testing

